/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/app/**/*.{ts,tsx}',
    './src/components/**/*.{ts,tsx}',
    '../../packages/ui/src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#002022',
        'on-tertiary-container': '#fffcff',
        'on-error': '#690005',
        'on-background': '#e1e2e7',
        'outline-variant': '#4b4455',
        'on-tertiary-fixed-variant': '#6c3a00',
        'secondary-fixed': '#7df4ff',
        secondary: '#d3fbff',
        'on-secondary-container': '#00686f',
        'surface-variant': '#323538',
        outline: '#968da1',
        'primary-fixed-dim': '#d5baff',
        'secondary-container': '#00eefc',
        'inverse-surface': '#e1e2e7',
        'on-secondary-fixed-variant': '#004f54',
        background: '#111417',
        'on-primary': '#42008a',
        'tertiary-fixed-dim': '#ffb779',
        'tertiary-fixed': '#ffdcc1',
        'on-tertiary-fixed': '#2e1500',
        'surface-container-high': '#272a2e',
        'surface-container': '#1d2023',
        error: '#ffb4ab',
        primary: '#d5baff',
        'surface-tint': '#d5baff',
        'on-secondary': '#00363a',
        surface: '#111417',
        'on-primary-fixed-variant': '#5e00c1',
        'secondary-fixed-dim': '#00dbe9',
        'on-surface-variant': '#cdc2d8',
        'inverse-on-surface': '#2e3134',
        'surface-dim': '#111417',
        'inverse-primary': '#7926e7',
        'on-primary-container': '#fffcff',
        'surface-container-lowest': '#0b0e11',
        'on-surface': '#e1e2e7',
        'primary-fixed': '#ecdcff',
        'on-tertiary': '#4c2700',
        'surface-container-low': '#191c1f',
        tertiary: '#ffb779',
        'surface-bright': '#37393d',
        'surface-container-highest': '#323538',
        'on-error-container': '#ffdad6',
        'primary-container': '#9147ff',
        'error-container': '#93000a',
        'tertiary-container': '#af6100',
        'on-primary-fixed': '#270057',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        'layout-gutter': '16px',
        base: '4px',
        md: '16px',
        lg: '24px',
        xl: '48px',
        'layout-margin': '24px',
      },
      fontFamily: {
        'body-lg': ['Inter'],
        'headline-md': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'headline-lg': ['Inter'],
        'display-lg': ['Inter'],
        'body-sm': ['Inter'],
        'label-md': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
