/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/app/**/*.{ts,tsx}',
    './src/components/**/*.{ts,tsx}',
    '../../packages/ui/src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Every token routes through a CSS variable defined in globals.css
        // (`:root` = dark default, `.light` = light overrides), so the whole
        // utility palette is theme-aware via the single `.light` class on
        // <html> — components never branch on the theme themselves.
        live: 'var(--md-live)',
        'on-live': 'var(--md-on-live)',
        online: 'var(--md-online)',
        'on-secondary-fixed': 'var(--md-on-secondary-fixed)',
        'on-tertiary-container': 'var(--md-on-tertiary-container)',
        'on-error': 'var(--md-on-error)',
        'on-background': 'var(--md-on-background)',
        'outline-variant': 'var(--md-outline-variant)',
        'on-tertiary-fixed-variant': 'var(--md-on-tertiary-fixed-variant)',
        'secondary-fixed': 'var(--md-secondary-fixed)',
        secondary: 'var(--md-secondary)',
        'on-secondary-container': 'var(--md-on-secondary-container)',
        'surface-variant': 'var(--md-surface-variant)',
        outline: 'var(--md-outline)',
        'primary-fixed-dim': 'var(--md-primary-fixed-dim)',
        'secondary-container': 'var(--md-secondary-container)',
        'inverse-surface': 'var(--md-inverse-surface)',
        'on-secondary-fixed-variant': 'var(--md-on-secondary-fixed-variant)',
        background: 'var(--md-background)',
        'on-primary': 'var(--md-on-primary)',
        'tertiary-fixed-dim': 'var(--md-tertiary-fixed-dim)',
        'tertiary-fixed': 'var(--md-tertiary-fixed)',
        'on-tertiary-fixed': 'var(--md-on-tertiary-fixed)',
        'surface-container-high': 'var(--md-surface-container-high)',
        'surface-container': 'var(--md-surface-container)',
        error: 'var(--md-error)',
        primary: 'var(--md-primary)',
        'surface-tint': 'var(--md-surface-tint)',
        'on-secondary': 'var(--md-on-secondary)',
        surface: 'var(--md-surface)',
        'on-primary-fixed-variant': 'var(--md-on-primary-fixed-variant)',
        'secondary-fixed-dim': 'var(--md-secondary-fixed-dim)',
        'on-surface-variant': 'var(--md-on-surface-variant)',
        'inverse-on-surface': 'var(--md-inverse-on-surface)',
        'surface-dim': 'var(--md-surface-dim)',
        'inverse-primary': 'var(--md-inverse-primary)',
        'on-primary-container': 'var(--md-on-primary-container)',
        'surface-container-lowest': 'var(--md-surface-container-lowest)',
        'on-surface': 'var(--md-on-surface)',
        'primary-fixed': 'var(--md-primary-fixed)',
        'on-tertiary': 'var(--md-on-tertiary)',
        'surface-container-low': 'var(--md-surface-container-low)',
        tertiary: 'var(--md-tertiary)',
        'surface-bright': 'var(--md-surface-bright)',
        'surface-container-highest': 'var(--md-surface-container-highest)',
        'on-error-container': 'var(--md-on-error-container)',
        'primary-container': 'var(--md-primary-container)',
        'error-container': 'var(--md-error-container)',
        'tertiary-container': 'var(--md-tertiary-container)',
        'on-primary-fixed': 'var(--md-on-primary-fixed)',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        'layout-gutter': '16px',
        base: '4px',
        md: '16px',
        lg: '24px',
        xl: '48px',
        'layout-margin': '24px',
      },
      fontFamily: {
        'body-lg': ['var(--font-sans)', 'sans-serif'],
        'headline-md': ['var(--font-sans)', 'sans-serif'],
        'body-md': ['var(--font-sans)', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-sans)', 'sans-serif'],
        'headline-lg': ['var(--font-sans)', 'sans-serif'],
        'display-lg': ['var(--font-sans)', 'sans-serif'],
        'body-sm': ['var(--font-sans)', 'sans-serif'],
        'label-md': ['var(--font-sans)', 'sans-serif'],
        'label-sm': ['var(--font-sans)', 'sans-serif'],
        'label-lg': ['var(--font-sans)', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
